packer {
  required_plugins {
    amazon = {
      version = ">= 1.2.6"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

variable "sys_pass" {
  default     = "SuperS3cr3t!!!!"
  description = "The password used to connect to the instance via WinRM."
  sensitive   = true
  type        = string
}

variable "sys_username" {
  type        = string
  description = "The plaintext username for authenticating"
  default     = "Aministrator"
}

variable "build_region" {
  default     = "us-east-1"
  description = "The region in which to retrieve the base AMI from and build the new AMI."
  type        = string
}

variable "jenkins_port" {
    default   = "8080"
    description = "Jenkins port on which to run."
    type = number
}

// locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "amazon-ebs" "windows-AMI" {
//   ami_name      = "windows-AMI-jenkins-${local.timestamp}"
  ami_name      = "windows-AMI-jenkins-var-1"
  instance_type = "t2.medium"
  region        = "us-east-1"
  communicator  = "winrm"
  source_ami_filter {
    filters = {
      name                = "Windows_Server-2022-English-Full-Base-*"
      root-device-type    = "ebs"
      virtualization-type = "hvm"
    }
    most_recent = true
    owners      = ["amazon"]
  }
  user_data_file = "./src/autogenerated_password_https_bootstrap.txt"

  //   force_deregister = true

  winrm_insecure = true
  winrm_password = "SuperS3cr3t!!!!"
  winrm_use_ssl  = true
  winrm_username = "Administrator"
  winrm_timeout  = "20m"
}

build {
  name = "build_windows_AMI"
  sources = [
    "source.amazon-ebs.windows-AMI"
  ]

  provisioner "powershell" {
    // environment_vars = [
    //     "NEW_PASS=${var.sys_pass}"
    // ]
    inline = [

      # Set administrator password
    // "net user Administrator $NEW_PASS",
    // "wmic useraccount where \"name='Administrator'\" set PasswordExpires=FALSE",
      # Install .NET Framework 3.5
      "Install-WindowsFeature -Name NET-Framework-Core",

      # Install Chocolatey
      "iex ((new-object net.webclient).DownloadString(\"https://chocolatey.org/install.ps1\"))",

      # Install JDK 11 
      "choco install openjdk --version=17.0.1 -y",
    ]
  }

  provisioner "powershell" {
    inline = [
      "Write-Host \"Your Java version is:\"",
      "java -version"
    ]
  }

  provisioner "powershell" {
    environment_vars = [
      "Port = ${var.jenkins_port}"
    ]
    inline = [
      # Install Jenkins using Chocolatey
      "choco install Jenkins -y",
      "Set-Service -Name Jenkins -StartupType Automatic",

      "Write-Host \"Set the port Jenkins uses\"",
      "$env:Config = Get-Content -Path \"$ENV:ProgramFiles\\Jenkins\\Jenkins.xml\"",
      "$env:NewConfig = $env:Config -replace \"--httpPort=[0-9]*\\s", "--httpPort=$ENV:Port \"",
      "Set-Content -Path \"$env:ProgramFiles\\Jenkins\\Jenkins.xml\" -Value $env:NewConfig -Force",
      "Start-Sleep -Seconds 30",
      "Write-Host \"Restarting service\"",
      "Restart-Service -Name Jenkins"
    ]
  }

  provisioner "powershell" {
    environment_vars = [
        "jenkins_port=${var.jenkins_port}",
        "password=${var.sys_pass}"
    ]
    scripts = [
      "./src/whitelist_win_port.ps1"
    ]
  }

}

